# Generated by Django 5.2.1 on 2025-06-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('U', 'Unisex')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender'], name='product_pro_gender_cf5d3a_idx'),
        ),
    ]
