# Generated by Django 5.2.1 on 2025-06-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
