# Generated by Django 5.2.1 on 2025-06-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
